### ISSUE TITLE
Have solid data process for students that transfer to another cohort

### ISSUE THREAD

**Issue by stevebrownlee** [stevebrownlee/learn-ops-client#47]
**Given** an instructor needs to change a student's cohort
**When** the instructor authenticates for the LP
**Then** there should be an affordance to search for an individual student that is enrolled in an active cohort

**Given** an instructor needs to change a student's cohort
**When** the instructor clicks on the student's name in their card
**Then** the overlay that appears should have a _Transfer Student_ affordance

**Given** is viewing the details of a student to perform a cohort transfer
**When** the instructor clicks _Transfer Student_ affordance
**Then** a dialog should be presented that lists all active cohorts, as a radio button group, and two buttons labeled _Client Side_ and _Server Side_, and an affordance labeled _Transfer Student_

**Given** an instructor has chosen an active cohort
**And** has chosen _Client Side_ or _Server Side_
**When** the instructor clicks on the _Transfer Student_ affordance
**Then** a message should display indiciating that the process was successful or failed
**And** if it was successful, the student overlay should immediately close and the student card list should be updated

## Client side transfer

* Reset points to 0 by removing all learning weight records
* Delete all existing assigned projects and assign initial project in initial book
* Remove all entries for assessments for student

## Server side transfer

* Delete all learning weight records for previous server-side course
* Delete all existing assigned projects for previous server-side course
* Remove all entries for assessments for previous server-side course

**Comment by trobinson1097** [comment]
2. [button/ link for transfer in student overlay] -> A link or button needs to be added to student overlay to allow an instructor to transfer a student.

**Comment by trobinson1097** [comment]
3. [transferring a student function] -> when clicked a new dialogue should appear that lists all active cohorts, server side and client side button, and affordance labeled transfer student.
